/**
 * Firebase Complete Content Import Script
 *
 * Imports books, sections, and paragraphs into Firestore
 * from the JSON files generated by extract_pdf_content.js
 */

const admin = require('firebase-admin');
const fs = require('fs');
const path = require('path');

// Initialize Firebase Admin if not already initialized
if (!admin.apps.length) {
  admin.initializeApp({
    credential: admin.credential.applicationDefault(),
  });
}

const db = admin.firestore();

/**
 * Import books to Firestore
 */
async function importBooks(books) {
  console.log('\n📚 Importing books...');

  const batchSize = 500;
  let importedCount = 0;

  for (let i = 0; i < books.length; i += batchSize) {
    const batch = db.batch();
    const batchBooks = books.slice(i, i + batchSize);

    for (const book of batchBooks) {
      const bookRef = db.collection('books').doc(book.id);
      const bookData = {
        ...book,
        created_at: admin.firestore.FieldValue.serverTimestamp(),
        updated_at: admin.firestore.FieldValue.serverTimestamp(),
      };
      delete bookData.id; // Remove id from data, it's already in the document path

      batch.set(bookRef, bookData, { merge: true });
      importedCount++;
    }

    await batch.commit();
    console.log(`  ✓ Imported batch ${Math.floor(i / batchSize) + 1}: ${importedCount}/${books.length} books`);

    if (i + batchSize < books.length) {
      await new Promise(resolve => setTimeout(resolve, 100));
    }
  }

  console.log(`✓ Successfully imported ${importedCount} books\n`);
  return importedCount;
}

/**
 * Import sections to Firestore
 */
async function importSections(sections) {
  console.log('📑 Importing sections...');

  const batchSize = 500;
  let importedCount = 0;

  for (let i = 0; i < sections.length; i += batchSize) {
    const batch = db.batch();
    const batchSections = sections.slice(i, i + batchSize);

    for (const section of batchSections) {
      const sectionRef = db.collection('sections').doc(section.section_id);
      const sectionData = {
        ...section,
        created_date: admin.firestore.FieldValue.serverTimestamp(),
      };

      batch.set(sectionRef, sectionData);
      importedCount++;
    }

    await batch.commit();
    console.log(`  ✓ Imported batch ${Math.floor(i / batchSize) + 1}: ${importedCount}/${sections.length} sections`);

    if (i + batchSize < sections.length) {
      await new Promise(resolve => setTimeout(resolve, 100));
    }
  }

  console.log(`✓ Successfully imported ${importedCount} sections\n`);
  return importedCount;
}

/**
 * Import paragraphs to Firestore
 */
async function importParagraphs(paragraphs) {
  console.log('📄 Importing paragraphs...');

  const batchSize = 500;
  let importedCount = 0;

  for (let i = 0; i < paragraphs.length; i += batchSize) {
    const batch = db.batch();
    const batchParagraphs = paragraphs.slice(i, i + batchSize);

    for (const paragraph of batchParagraphs) {
      const paragraphRef = db.collection('paragraphs').doc(paragraph.paragraph_id);
      const paragraphData = {
        ...paragraph,
        created_date: admin.firestore.FieldValue.serverTimestamp(),
      };

      batch.set(paragraphRef, paragraphData);
      importedCount++;
    }

    await batch.commit();

    // Progress indicator
    if ((i + batchSize) % 5000 === 0 || i + batchSize >= paragraphs.length) {
      console.log(`  ✓ Progress: ${importedCount}/${paragraphs.length} paragraphs`);
    }

    if (i + batchSize < paragraphs.length) {
      await new Promise(resolve => setTimeout(resolve, 100));
    }
  }

  console.log(`✓ Successfully imported ${importedCount} paragraphs\n`);
  return importedCount;
}

/**
 * Load all paragraph files
 */
function loadAllParagraphs() {
  const paragraphs = [];
  let partNumber = 1;

  while (true) {
    const filename = `firebase_paragraphs_part${partNumber}.json`;
    const filepath = path.join(__dirname, filename);

    if (!fs.existsSync(filepath)) {
      break;
    }

    const data = JSON.parse(fs.readFileSync(filepath, 'utf8'));
    paragraphs.push(...data.paragraphs);
    console.log(`  Loaded ${filename}: ${data.paragraphs.length} paragraphs`);
    partNumber++;
  }

  return paragraphs;
}

/**
 * Main import function
 */
async function importCompleteContent() {
  console.log('\n' + '='.repeat(70));
  console.log('  Firebase Complete Content Import');
  console.log('  Path of Light - Islamic Books Library');
  console.log('='.repeat(70));

  try {
    // Check if complete import file exists
    const completeFilePath = path.join(__dirname, 'firebase_complete_import.json');

    if (!fs.existsSync(completeFilePath)) {
      console.error('\n❌ Error: firebase_complete_import.json not found!');
      console.log('Please run: node extract_pdf_content.js first\n');
      process.exit(1);
    }

    console.log('\n📂 Loading data files...');
    const completeData = JSON.parse(fs.readFileSync(completeFilePath, 'utf8'));

    console.log('\n📊 Data Summary:');
    console.log(`  Books: ${completeData.books.length}`);
    console.log(`  Sections: ${completeData.sections.length}`);
    console.log(`  Paragraphs (in complete file): ${completeData.paragraphs.length}`);

    // Load all paragraph files
    console.log('\n📄 Loading paragraph files...');
    const allParagraphs = loadAllParagraphs();
    console.log(`  Total paragraphs loaded: ${allParagraphs.length}`);

    console.log('\n⚠️  Starting import to Firestore...');
    console.log('This may take several minutes depending on content size.\n');

    const startTime = Date.now();

    // Import in order: books -> sections -> paragraphs
    const booksImported = await importBooks(completeData.books);
    const sectionsImported = await importSections(completeData.sections);
    const paragraphsImported = await importParagraphs(allParagraphs);

    const endTime = Date.now();
    const duration = ((endTime - startTime) / 1000).toFixed(2);

    // Final summary
    console.log('\n' + '='.repeat(70));
    console.log('✨ Import Completed Successfully!');
    console.log('='.repeat(70));
    console.log(`📚 Books imported: ${booksImported}`);
    console.log(`📑 Sections imported: ${sectionsImported}`);
    console.log(`📄 Paragraphs imported: ${paragraphsImported}`);
    console.log(`⏱️  Total time: ${duration} seconds`);
    console.log('='.repeat(70));

    console.log('\n✅ Next steps:');
    console.log('1. Verify data in Firebase Console');
    console.log('2. Upload PDF files to Firebase Storage (islamic_books/)');
    console.log('3. Update book content_status to "published" when ready');
    console.log('4. Test in the Path of Light app\n');

  } catch (error) {
    console.error('\n❌ Fatal error during import:', error);
    console.error(error.stack);
    process.exit(1);
  }
}

/**
 * Verify existing data before import
 */
async function checkExistingData() {
  console.log('\n🔍 Checking existing Firestore data...\n');

  try {
    const [booksSnap, sectionsSnap, paragraphsSnap] = await Promise.all([
      db.collection('books').limit(1).get(),
      db.collection('sections').limit(1).get(),
      db.collection('paragraphs').limit(1).get(),
    ]);

    console.log(`  Existing books: ${booksSnap.size > 0 ? 'Found' : 'None'}`);
    console.log(`  Existing sections: ${sectionsSnap.size > 0 ? 'Found' : 'None'}`);
    console.log(`  Existing paragraphs: ${paragraphsSnap.size > 0 ? 'Found' : 'None'}`);

    if (booksSnap.size > 0 || sectionsSnap.size > 0 || paragraphsSnap.size > 0) {
      console.log('\n⚠️  Warning: Existing data found. This import will merge/update existing records.\n');
    }
  } catch (error) {
    console.error('  Could not check existing data:', error.message);
  }
}

/**
 * Main execution
 */
async function main() {
  await checkExistingData();
  await importCompleteContent();
  process.exit(0);
}

// Run the script
main().catch(error => {
  console.error('Unhandled error:', error);
  process.exit(1);
});
