// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXgMptwjtbdUzqQgQl6xljDv8Jd-4P5wA',
    appId: '1:364592189326:android:156b872aa76ca45d0a5edf',
    messagingSenderId: '364592189326',
    projectId: 'path-of-light-9226e',
    databaseURL: 'https://path-of-light-9226e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'path-of-light-9226e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxOjuvMslsqA_F3QF8XCYrvNvFBjlPGgI',
    appId: '1:364592189326:ios:73eba7b8f2dc7c010a5edf',
    messagingSenderId: '364592189326',
    projectId: 'path-of-light-9226e',
    databaseURL: 'https://path-of-light-9226e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'path-of-light-9226e.firebasestorage.app',
    iosBundleId: 'com.example.pathOfLight',
  );
}
